# Generated by Django 3.2.5 on 2022-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('zkaddr', models.CharField(max_length=20)),
                ('dashboardurl', models.CharField(max_length=50)),
                ('proxy_list', models.CharField(default=None, max_length=200)),
                ('group_num', models.IntegerField()),
                ('sentinel_list', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=20)),
                ('ishealth', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=30)),
                ('server_num', models.IntegerField()),
                ('server_ip', models.CharField(max_length=30)),
                ('replica_group', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('action_state', models.BooleanField(default='synced')),
            ],
        ),
        migrations.CreateModel(
            name='Proxys',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('proxy_addr', models.CharField(max_length=100)),
                ('proxy_max_clients', models.CharField(default=None, max_length=6)),
                ('admin_addr', models.CharField(default=None, max_length=40)),
                ('product_name', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=20)),
                ('proxy_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentinel',
            fields=[
                ('sgid', models.AutoField(primary_key=True, serialize=False)),
                ('sen_server', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='topom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_addr', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
