# Generated by Django 3.2.5 on 2022-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codis_mon_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentinel',
        ),
        migrations.AddField(
            model_name='clusters',
            name='sent_sync',
            field=models.BooleanField(default=True),
        ),
    ]
