# Generated by Django 3.1.5 on 2021-01-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='sgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.grades'),
        ),
    ]
