# Generated by Django 3.1.5 on 2021-01-11 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AlterModelManagers(
            name='students',
            managers=[
                ('stuObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='grades',
            old_name='bboynum',
            new_name='gboynum',
        ),
        migrations.AlterField(
            model_name='students',
            name='sgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp1.grades'),
        ),
    ]
